tinc+etcd

diff --git a/scripts/launch b/scripts/launch
--- a/scripts/launch
+++ b/scripts/launch
@@ -1,105 +1,70 @@
 #!/bin/sh
 
-name=$1
-image=${2:-my/base/arch}
-nodes=$(docker ps -q | wc -l)
-
-if [ -z $name ]; then
-	echo "please specify --name"
-	exit
+name="$1"
+if [ -z "$name" ]; then
+	echo "empty name"
+	exit 1
 fi
 
-args="--name=$name"
+nexusip=$(docker inspect -f '{{.NetworkSettings.IPAddress}}' $(hostname) 2>/dev/null)
 
-if [ $nodes -eq 0 ]; then
-	host="$(hostname)"
-	args="--net=host $args"
+if [ "$name" = "nexus" ]; then
+	if [ ! -z "$nexusip" ]; then
+		echo "nexus is already running on $(hostname) @ $nexusip"
+		exit 1
+	fi
+	docker run -dit \
+		-p 2380:2380 -p 53:53/udp \
+		--device /dev/net/tun \
+		--cap-add SYS_ADMIN \
+		--cap-add NET_ADMIN \
+		--cap-add SYS_RESOURCE \
+		-v /var/run/docker.sock:/docker.sock \
+		-v /usr/bin/docker:/usr/bin/docker \
+		-v /sys/fs/cgroup:/sys/fs/cgroup:ro \
+		--name $(hostname) \
+		-h $(hostname) \
+		my/cluster/nexus
+	echo "Waiting for nexus"
+	while ! docker exec $(hostname) pgrep tincd >/dev/null; do
+		echo -n "."
+		sleep 1
+	done
+	echo ""
+	echo "nexus started as $(hostname)"
 else
-	host="$(hostname)-$name"
-	args="-h $host $args"
+	if [ -z "$nexusip" ]; then
+		echo "Could not find nexus ip. Is nexus running?"
+		exit 1
+	fi
+	fullname=$(hostname)-$name;
+	if docker inspect -f 'yes' $fullname; then
+		echo "Container already exists: $fullname"
+		exit 1
+	fi
+
+	docker run -dit \
+		--device /dev/net/tun \
+		--cap-add SYS_ADMIN \
+		--cap-add NET_ADMIN \
+		--cap-add SYS_RESOURCE \
+		-e TINC_INVITE=$tincinvite \
+		-v /sys/fs/cgroup:/sys/fs/cgroup:ro \
+		--name $fullname \
+		-h $fullname \
+		--add-host nexus:$nexusip \
+		my/cluster/node
+
+	echo "Waiting for node"
+	tinchost=$(echo $fullname | sed 's/-/_/g')
+	tincinvite=$(docker exec $(hostname) tinc -n cluster invite $tinchost)
+	echo $tincinvite
+	docker exec $fullname tinc -n cluster join $tincinvite
+	while ! docker exec $fullname sh -c "test /etc/tinc/cluster/tinc.conf"; do
+		sleep 1
+	done
+	echo ""
+	docker exec $fullname sh -c "echo 'Address = nexus' >> /etc/tinc/cluster/hosts/$(hostname)"
+	docker exec $fullname systemctl restart clusterinit
+	echo "node started as $fullname"
 fi
-
-docker run -dit --cap-add SYS_ADMIN  --cap-add NET_ADMIN --cap-add SYS_RESOURCE \
-       --device /dev/net/tun \
-       -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
-       -v /home/data:/home \
-       -v /home/cluster:/opt/cluster \
-       $args $image
-
-desc="${host}=http://${host}.local:2380"
-if [ $nodes -gt 0 ]; then
-	desc=$desc,$(docker exec $(hostname) sh -c 'echo $(etcdctl ls /cluster/nodes | sed "s|.*/||g;s|.*|&=http://&.local:2380|g")' | tr ' ' ',')
-	mode=existing
-else
-	mode=new
-fi
-
-
-config="$(cat <<EOF
-ETCD_NAME="$host"
-ETCD_INITIAL_CLUSTER_STATE="$mode"
-ETCD_INITIAL_CLUSTER="$desc"
-ETCD_ADVERTISE_CLIENT_URLS="http://${host}.local:2379"
-ETCD_INITIAL_ADVERTISE_PEER_URLS="http://${host}.local:2380"
-ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"
-ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380"
-EOF
-)"
-
-docker exec "$name" sh -c "echo '$config' > /etc/conf.d/etcd"
-
-tinchost=$(echo $host | sed 's/-/_/g')
-if [ $nodes -eq 0 ]; then
-	docker exec $name tinc -n cluster init $tinchost
-	docker exec $name sh -c "echo Mode = switch >> /etc/tinc/cluster/tinc.conf"
-	docker exec $name sh -c "echo Address = 172.17.0.1 >> /etc/tinc/cluster/hosts/$tinchost"
-else
-	invite=$(docker exec $(hostname) tinc -n cluster invite $tinchost | sed 's|^[^/]*/|172.17.0.1/|')
-	docker exec $name tinc join $invite
-	docker exec $name sed '/ConnectTo/d' -i /etc/tinc/cluster/tinc.conf
-fi
-
-docker exec $name sh -c "echo 'avahi-autoipd -wD \$INTERFACE' > /etc/tinc/cluster/tinc-up"
-
-docker exec $name systemctl enable tinc@cluster
-docker exec $name systemctl start tinc@cluster
-
-if [ $nodes -eq 0 ]; then
-	docker exec $name systemctl enable etcd
-	docker exec $name systemctl start etcd
-	docker exec $name etcdctl --no-sync mkdir /cluster
-	docker exec $name etcdctl --no-sync mkdir /cluster/nodes
-	docker exec $name etcdctl --no-sync mkdir /cluster/nodes/$host
-else 
-	docker exec $(hostname) etcdctl mkdir /cluster/nodes/$host
-fi
-
-conns="$(docker exec $(hostname) etcdctl ls /cluster/nodes | grep -v "/${host}\$" | sed 's|.*/||g;s|.*|ConnectTo = &|g')"
-if [ ! -z "$conns" ]; then
-	docker exec "$name" sh -c "echo '$conns' >> /etc/tinc/cluster/tinc.conf"
-fi
-
-while true; do
-	docker exec $name ip addr show cluster | grep -q "inet " && break
-	sleep 1
-done
-if [ $nodes -gt 0 ]; then
-	( \
-		docker exec $(hostname) touch /tmp/ack_$host; \
-		docker exec $(hostname) tail --follow=name /tmp/ack_$host 2>/dev/null; \
-		docker exec $name systemctl enable etcd.service; \
-		docker exec $name systemctl start etcd.service; \
-	) &
-	docker exec $(hostname) etcdctl mk /cluster/nodes/$host/init $host
-	docker exec "$name" systemctl enable sshd
-	docker exec "$name" systemctl start sshd
-	wait
-fi
-
-docker exec $name sh -c "echo 'etcdctl set /cluster/nodes/\$(hostname)/address \$(ip addr show \$INTERFACE | awk \"/inet /{print \\\$2; exit}\" | sed \"s|/.*||g\")' >> /etc/tinc/cluster/tinc-up"
-docker exec $name systemctl enable nodewatcher.service
-docker exec $name systemctl start nodewatcher.service
-docker exec $(hostname) sh -c "etcdctl set /cluster/nodes/$host/address \$(ip addr show \$INTERFACE | awk \"/inet /{print \$2; exit}\" | sed \"s|/.*||g\")"
-#docker exec $(hostname) sh -c 'etcdctl set /cluster/nodes/$host/address \$\(ip addr show cluster \| awk "/inet /{print \$2; exit}" \| sed "s|/.*||g" \)'
-
-echo $host ready
